### ISSUE TITLE
Not Signed

### ISSUE THREAD

**Issue by selectplaya** [mtanneryd/ef6-bulk-operations#15]
When compiling my solution I get the following error as the assembly is not signed.

CSC : error CS8002: Referenced assembly 'Tanneryd.BulkOperations.EF6, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by mtanneryd** [comment]
I have no current plans to sign the assemblies. If you need signed assemblies in your project just download the code, add it to your project and sign it yourself.
