### ISSUE TITLE
BulkInsert is not thread safety

### ISSUE THREAD

**Issue by simai4** [mtanneryd/ef6-bulk-operations#16]
Helloy,  @mtanneryd.

If I execute many BulkInsert in one table in many threads (parrallel executing BulkInsert), I have Exception("More id values generated than we had entities. Something went wrong, try again.").

It happens because the increment of the primary key (user integer) and the number of inserted records are compared, but they may differ when the insertion is parallel.

**Comment by mtanneryd** [comment]
Hi!

Thanks for your feedback. Which version are you using?

**Comment by simai4** [comment]
Hi,
I'm using 1.2.2 version.

**Comment by komrados** [comment]
Hi, 
I'm also experiencing this problem at version 1.2.3

**Comment by mtanneryd** [comment]
When you say  "user integer", exactly what do you mean? Have you defined your own type?

**Comment by mtanneryd** [comment]
Thinking about this a bit more and reading the original bug report by simai4 again, I realize that I need to replace the "select ident...." based way of matching generated primary keys with the merge-based variant. I'll try to get it fixed and tested before the weekend.

Thanks for the valuable feedback!
