### ISSUE TITLE
.net Standard / EF6.3

### ISSUE THREAD

**Issue by profet23** [mtanneryd/ef6-bulk-operations#26]
Any chance of adding a .net standard target for this project (would need to change to the EF6.3 package)?

I would like to continue to use this library as we migrate to .net core 3.

More info here:
https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/#what-s-new-in-ef-6-3

**Comment by mtanneryd** [comment]
Hi Ben and thanks for your feedback. I’ll try to get it fixed during the holidays.

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen

**Comment by BRiley01** [comment]
Hi Måns ,
  I see you created a separate branch for 1.4.0 with support for .net standard.  It seems to pass it's tests when run locally, just curious when you might publish this branch to nuget?

**Comment by mtanneryd** [comment]
Hi!

As soon as I have been able to run some real world tests on it, or get
enough feedback from users doing just that. Hope to get it out in a week or
two.

/Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den mån 6 jan. 2020 kl 17:31 skrev BRiley01 <notifications@github.com>:

**Comment by BRiley01** [comment]
Great, thanks!

**Comment by n-valchev** [comment]
Hey @mtanneryd, is there any progress on this? I see there has been an experimental version for the last couple of months, but do you intend to mark it as official?

Thanks a lot!

**Comment by mtanneryd** [comment]
Indeed I do! I was planning to make some final tests last week but the
corona situation got the better of me. Also, I have a teenage son in the US
and we're currently trying to get him home but the recent travel ban makes
it a bit complicated and it has sort of consumed all of my time. Hope to
get it done later this week or the next.

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den tis 17 mars 2020 kl 13:11 skrev Nikolay Valchev <
notifications@github.com>:

**Comment by mtanneryd** [comment]
Release 1.4.0 resolves this issue.
