### ISSUE TITLE
Regex to get table name gives empty string.

### ISSUE THREAD

**Issue by tallalkazmi** [mtanneryd/ef6-bulk-operations#27]
The following Regex that you are using gives empty string:
`var regex = new Regex(@"FROM (?<table>[\[\w@$#_\. \]]+) AS \[\w+\]$")` and this error is not handled.

The SQL statement generated from my code is:
`SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Identifier] AS [Identifier], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[Latitude] AS [Latitude], 
    [Extent1].[Longitude] AS [Longitude], 
    [Extent1].[FIR] AS [FIR], 
    [Extent1].[UIR] AS [UIR], 
    [Extent1].[ICAO] AS [ICAO], 
    [Extent1].[MagneticVariation] AS [MagneticVariation], 
    [Extent1].[Frequency] AS [Frequency], 
    [Extent1].[CountryName] AS [CountryName], 
    [Extent1].[CountryId] AS [CountryId], 
    [Extent1].[StateId] AS [StateId], 
    [Extent1].[CityId] AS [CityId], 
    [Extent1].[IsActive] AS [IsActive]
    FROM [dbo].[Points] AS [Extent1]
    WHERE ([Extent1].[IsActive] = @DynamicFilterParam_000001) OR (@DynamicFilterParam_000002 IS NOT NULL)`

Ill generate a pull request fixing this issue and added additional exception handling, please be kind enough to merge this and release on nuget. Thanks.

File: DbContextExtensions.cs
LIne: 2201

![Capture](https://user-images.githubusercontent.com/31439236/71573604-31930580-2afe-11ea-8c60-c4e04f3af5fa.JPG)

**Comment by tallalkazmi** [comment]
I am not able to commit changes. Here are the changes which i did to make it work:

`
 public static TableName GetTableName(this DbContext ctx, Type t)
        {
            var dbSet = ctx.Set(t);
            var sql = dbSet.ToString();

            //Gives empty tablename
            //var regex = new Regex(@"FROM (?<table>[\[\w@$#_\. \]]+) AS \[\w+\]$");

            //Simplified Regex to get everything between FROM and first occurrence of AS then trim the string value.
            var regex = new Regex(@"FROM(?<table>.*?)AS");
            var match = regex.Match(sql);
            var name = match.Groups["table"].Value.Trim();

            //Added empty tablename exception handling.
            if(string.IsNullOrWhiteSpace(name))
                throw new ArgumentException($"Failed to parse tablename. Bulk operation failed.");

            var n = name.Replace("[", "").Replace("]", "");
            var m = Regex.Match(n, @"(.*)\.(.*)");
            if (m.Success)
            {
                return new TableName { Schema = m.Groups[1].Value, Name = m.Groups[2].Value };
            }

            m = Regex.Match(n, @"(.*)");
            if (m.Success)
            {
                return new TableName { Schema = "dbo", Name = m.Groups[1].Value };
            }

            throw new ArgumentException($"Failed to parse tablename {name}. Bulk operation failed.");
        }
`

**Comment by mtanneryd** [comment]
Thanks for the feedback. I’ll check it out asap.

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen

**Comment by mtanneryd** [comment]
Tallal Kazmi, which version are you using?

**Comment by tallalkazmi** [comment]
The latest one. 1.3.0
[https://www.nuget.org/packages/Tanneryd.BulkOperations.EF6/](url)

**Comment by mtanneryd** [comment]
1.3.1-beta1 was just pushed. It should fix the problem you had. I
refactored the regular expression. I've had previous reports where this has
failed with some rather complex schemas and such. Had to make sure those
still worked. Let me know if this resolves your issues so that I can push
an official 1.3.1.


Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den mån 30 dec. 2019 kl 20:09 skrev Tallal Kazmi <notifications@github.com>:

**Comment by tallalkazmi** [comment]
Yes, the 1.3.1-beta1 fixes the issue. You can move to an official 1.3.1 so I can too move my code to production. Thanks for your prompt response and a great library.
