### ISSUE TITLE
Database generated Guid as Primary Keys

### ISSUE THREAD

**Issue by mihaivader** [mtanneryd/ef6-bulk-operations#3]
Hello,

Thank you for the great work. These helpers that you put together are really helpful.
Any plans to support database generated Guid as Primary Keys?
Or any suggestions on how to do it?

Thank you :)

**Comment by mihaivader** [comment]
Hello, again.
I've inserted a temporary IDENTITY Column on my tables which I drop after the query executes.
Works of Parent - Child relationship.
I'll try for more complex scenarios and I'll post here any updates.

**Comment by mtanneryd** [comment]
Hi and thanks for your feedback.

At some point in time generated GUID primary keys actually did work. I might have lost that functionality recently for some reason. I'll have a look this week.

/Måns

**Comment by mihaivader** [comment]
The Guid generated Ids work fine with the Temporary Identity column (I don't know if this is the best way to do it).

Also, I'm having some issues with another scenario:
I have a "Blog" which is one-to-many with "Post" which many-to-many to "Keywords", but for some reason, in the PostKeywords table it's trying to insert (PostId, KeyworkdId) - (Guid, Empty.Guid)

Any ideas?
Thanks

**Comment by mtanneryd** [comment]
If you could post the code for those three classes I could run some tests.

**Comment by mihaivader** [comment]
Yes, I'm talking about database generated Guid (newsequentialid())
As for the many to many relationship which isn't working for me,

[Table("Blog")]
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            Posts = new HashSet<Post>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }

[Table("Post")]
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            Keywords = new HashSet<Keyword>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        public Guid BlogId { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Content { get; set; }

        public virtual Blog Blog { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keyword> Keywords { get; set; }
    }

public partial class Keyword
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Keyword()
        {
            Posts = new HashSet<Post>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }

protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
                .HasMany(e => e.Posts)
                .WithRequired(e => e.Blog)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<Post>()
                .HasMany(e => e.Keywords)
                .WithMany(e => e.Posts)
                .Map(x =>
                    {
                        x.ToTable("PostKeywords");
                        x.MapLeftKey("PostId");
                        x.MapRightKey("KeywordId");
                    });
        }

**Comment by mtanneryd** [comment]
I think I have a fix for your many-to-many issue. I tried it on a similar piece of code and could replicate and fix the issue. I haven't tried it on your specific code yet though.

**Comment by mihaivader** [comment]
Nice :)

**Comment by mihaivader** [comment]
Closed it accidentally.  
I also made some changes around differences between property names and column names.
Also added support for SqlGeometry and SqlGeography types.
And support for Guid type for Id (database generated).

Are you interested in receiving these changes? :)

**Comment by mihaivader** [comment]
I'll email you tomorrow :) 
If you could also update the code with the solution from Guid generated Ids, that would be great

**Comment by mihaivader** [comment]
Hey.
Any updates on the Many to Many relationship? 
Also have you considered supporting One to One relationships where the ID (database generated) from a table is also ID in another table? A PK , FK constraint.

Thanks

**Comment by mtanneryd** [comment]
Hi!

The code currently in the repository works fine at least for the many-to-many relationships I have. It is a simple join table where identity primary keys from two tables form the primary key in the join table. The system I use this extension on also have several one-to-one relationships and they work just fine.

So, please try the latest version and let me know if it works or not. If not, please provide your failing example setup. I've had to deal with sick kids this week so I have been a bit pressed for time. As soon as possible I will create more test cases and verify that everything you have reported works as expected.

Again, thanks for your most welcome and very valuable feedback!

**Comment by mihaivader** [comment]
Hi :)

I've retried the many to many relation ship from scratch and it's working. I might have just screwed up the mappings in EF.
I've also got the One to One working with IDs that are both PK and FK and database generated. I had to make some minor tweaks.
I can resend you everything if you wish.

Cheers,
Mihai

**Comment by mtanneryd** [comment]
The latest commit contains a fix for generated guid primary keys. It was a bit more complicated than I first expected but I think the current solution will work fine for all cases.

**Comment by mihaivader** [comment]
Thanks for that :) I'll have a look

**Comment by mihaivader** [comment]
I'll have a look now. i'll just have to merge your changes into mine, as I have some extra things added to my local version:
- SQL Spatial types
- Differences between C# property names and SQL column names
- PK which are also FK

**Comment by mtanneryd** [comment]
Both "Differences between C# property names and SQL column names" and "PK which are also FK" should work though. I have plenty of that in the software where I use this extension. If you have examples of that that does not work I would be happy to get some samples!

**Comment by mtanneryd** [comment]
As far as I know and remember this has been fixed. If not, please reopen the issue.
