### ISSUE TITLE
BulkInsertAll null reference exception on EntityType with EF6.2.0 + .net 4.6.2

### ISSUE THREAD

**Issue by michalhainc** [mtanneryd/ef6-bulk-operations#31]
Hi, thank you for your work on this project, 
I built it from sources and discovered an issue. 
Here in this place in [DbContextExtensions.cs on line 2319](https://github.com/mtanneryd/ef6-bulk-operations/blob/03f3dad551b6746d5dccc4c6c32e3fc628241cb4/Tanneryd.BulkOperations.EF6/Tanneryd.BulkOperations.EF6/DbContextExtensions.cs#L2319) the typeMapping.EntityType is null and throws a null reference exception.

**Comment by michalhainc** [comment]
Created a [pull request](https://github.com/mtanneryd/ef6-bulk-operations/pull/32) but I would say it is not generic at all... but for what I need it works (bulk insert into dummy table without any navigation properties)

**Comment by mtanneryd** [comment]
Thank you Michal!

I'll have a look asap. Planning to upload a new release during easter.

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den fre 10 apr. 2020 kl 15:13 skrev Michal Hainc <notifications@github.com>:

**Comment by michalhainc** [comment]
Nothing to thank for, as I said, it is probably too stupid and ignorant fix, but enough for my usage, I should probably provide my model (at least part of it as unit test) as I suspect there might be something wrong with it...

**Comment by mtanneryd** [comment]
Please do provide your model. I tried to replicate it but could not. Your
model and what you were trying to do would be most helpful.

/Måns
Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den fre 10 apr. 2020 kl 19:58 skrev Michal Hainc <notifications@github.com>:

**Comment by michalhainc** [comment]
Hello, I have to apologize, now when I created a small console app to reproduce the issue, I cannot, it is working fine. So apparently I have to dive into our solution and start searching for the problem.

**Comment by michalhainc** [comment]
Sorry, previously I wrote that I cannot reproduce the issue in a minimum-reproduction-app, but then I remembered I am trying it over my fork where I added this "blind-fix" so it worked. When I reverted my fork now to your state it is nicely reproducible.
The console app for reproducing the issue is located in the [master branch of my fork](https://github.com/michalhainc/ef6-bulk-operations/tree/master/Tanneryd.BulkOperations.EF6/issue-31-reproduction)...

**Comment by mtanneryd** [comment]
Thanks!

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen

**Comment by michalhainc** [comment]
I would say the root of this problem is the fact that my model was created using "model-first" approach but I have too less knowledge of EF...

**Comment by mtanneryd** [comment]
Yeah. It seems as if the mapping info that I get from the dbcontext is
slightly different for model first and code first approaches, at least when
it comes to navigation props. The current version has only been tested
against code first situations so this is an interesting error. I need to
create model first versions of all tests and see what happens.

/Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd

*https://github.com/mtanneryd/ef6-bulk-operations
<https://github.com/mtanneryd/ef6-bulk-operations>*



Den lör 11 apr. 2020 kl 17:53 skrev Michal Hainc <notifications@github.com>:

**Comment by mtanneryd** [comment]
This was a problem related to table inheritance and not to the model first approach. As a result I have added new experimantal support for TPH and added multiple versions of the unit tests using both model first and code first approaches. A new beta nuget will be published today or tomorrow.

**Comment by michalhainc** [comment]
Thank you, I will test once the update is out

**Comment by mtanneryd** [comment]
I believe this issue has been fixed. Please reopen if I am mistaken.
