### ISSUE TITLE
Problem with BulkInsert when having column name like In or As

### ISSUE THREAD

**Issue by MatGauthier** [mtanneryd/ef6-bulk-operations#7]
Hi @mtanneryd, thank you for the effort you put into this library. I was importing chemical analysis in a Datawaharehouse having column name like "As" and "In" that throw error when they are not between [].  There's missing [] in some function of DbContextExtensions that involve ColumnName.

Here's a version of DbContextExtensions that fixes the problem but did it very quick and didn't do many many test with it. Next time I will take the time to do a pullrequest to ease the merge job.

[DbContextExtensions.zip](https://github.com/mtanneryd/ef6-bulk-operations/files/2310167/DbContextExtensions.zip)

**Comment by mtanneryd** [comment]
Hi!

Have you tried the latest prerelease version? There should be fixes for
exactly that problem in the latest release. I will have a look at your
changes nevertheless and see if there is something still missing.

Thanks for your feedback!

/Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen


2018-08-22 13:55 GMT+02:00 MatGauthier <notifications@github.com>:

**Comment by MatGauthier** [comment]
Hi, 

In fact, I downloaded the master code monday august 21 to apply the fix I sent to you. So if the prerelease uses master, yep I tested it.

Cheers

**Comment by mtanneryd** [comment]
Interesting. Again, thanks!

/Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd
https://www.facebook.com/matkollen


2018-08-23 15:31 GMT+02:00 MatGauthier <notifications@github.com>:

**Comment by mtanneryd** [comment]
These issues should be fixed now so I'm closing the issue. Please reopen it if you find that these changes were not enough. Thanks for all your feedback and contributions.
