### ISSUE TITLE
BulkUpdateAll error with use proxy type.

### ISSUE THREAD

**Issue by simai4** [mtanneryd/ef6-bulk-operations#8]
Hi @mtanneryd.

I'm get entities from entity fremwork, modify and BulkUpdateAll(). I have exception in runtime. The problem is that entity fremwork returns a collection of proxy types. 

Solution: add stringin DbContextExtensions in GetMappings method on 1794 row
"t = ObjectContext.GetObjectType(t);"

**Comment by mtanneryd** [comment]
Thanks!

I have reproduced the problem and corrected it with your suggested fix. I have committed the fix as well as some other recent bug fixes. A new nuget release will be available shortly.

**Comment by mtanneryd** [comment]
This has been fixed and will be included in the upcoming 1.2.2 release.
